### PR TITLE
WIP: Add editorconfig

### PR DESCRIPTION
**Pull request by timdeschryver**
# Info
This Pull Request is related to issue no. #122 

# Changes
Add `.editorconfig`

Once we agreed on the config and when the other PRs are accepted, I will run this on the project (otherwise we'll have merge conflicts 😅).

You can take a look at the [.NET coding convention](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) if you want to change something.

### CODE REVIEW

**Review by GooRiOn — DISMISSED** [review]

**Comment by GooRiOn** [comment]
Can I merge this one or there's something else that needs to be done ?

**Comment by timdeschryver** [comment]
@GooRiOn not yet.
If this config is good for us, I'd like to run an auto fix on all files when every other PR is merged.
If thats OK for you ofcourse.

**Comment by GooRiOn** [comment]
I guess you're ready to go with this PR :)

**Comment by timdeschryver** [comment]
These changes are a little more than I expected 😅

**Comment by GooRiOn** [comment]
Nice one :D

**Review by GooRiOn — APPROVED** [review]

**Pull request merged**
